# Site settings
name: Provencesl的博客
email: provencesl6@gmail.com
author: provencesl
url: 
resume_site: 
github: https://github.com/provencesl/
baseurl: ""  #根目录
description: WonderFul Game,Funny Life。
motto: 我们笑着说再见，却深知再见遥遥无期。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 拥抱这世界。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
gem: [jekyll,jekyll-paginate,github-pages]
plugins: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: provencesl
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : provencesl
